# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                ("tokens_to_approve", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Signature"),
                            ("signed", "Signed - Awaiting Transaction"),
                            ("approved", "Approved on Blockchain"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("spender_address", models.CharField(max_length=42)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "approval_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                ("course_name", models.CharField(max_length=255)),
                ("completion_date", models.DateField()),
                ("certificate_hash", models.CharField(max_length=255, unique=True)),
                (
                    "nft_token_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "nft_contract_address",
                    models.CharField(blank=True, max_length=42, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Mint"),
                            ("minting", "Minting in Progress"),
                            ("minted", "Minted"),
                            ("failed", "Minting Failed"),
                            ("verified", "ZKP Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("zk_proof_hash", models.TextField(blank=True, null=True)),
                (
                    "ipfs_metadata_hash",
                    models.CharField(
                        blank=True,
                        help_text="IPFS hash for certificate metadata",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Certificate metadata (issuer, skills, score, etc.)",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("minted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "certificates",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="OnChainPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                ("course_name", models.CharField(max_length=255)),
                (
                    "tokens_amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("user_wallet_address", models.CharField(max_length=42)),
                ("platform_treasury_address", models.CharField(max_length=42)),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain transaction hash",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                (
                    "gas_used",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=18, null=True
                    ),
                ),
                (
                    "gas_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confirmation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of blocks confirming this transaction",
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "on_chain_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartContractConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("token", "ERC20 Token"),
                            ("certificate", "ERC721 Certificate NFT"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("contract_address", models.CharField(max_length=42, unique=True)),
                ("contract_abi", models.JSONField(help_text="Contract ABI")),
                ("deployment_hash", models.CharField(max_length=255)),
                ("block_number", models.BigIntegerField()),
                ("network", models.CharField(default="sepolia", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "smart_contract_configs",
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment_confirmed", "Payment Confirmed"),
                            ("payment_failed", "Payment Failed"),
                            ("certificate_minted", "Certificate Minted"),
                            ("certificate_burned", "Certificate Burned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=255, unique=True)),
                ("block_number", models.BigIntegerField()),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "blockchain_webhook_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
