# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blockchain_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onchainpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="on_chain_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["transaction_hash"], name="blockchain__transac_3564c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["event_type"], name="blockchain__event_t_e955c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["user", "status"], name="approval_re_user_id_e45a9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["user", "-issued_at"], name="certificate_user_id_a74be4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["status"], name="certificate_status_a01db5_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["nft_token_id"], name="certificate_nft_tok_b2ed25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onchainpayment",
            index=models.Index(
                fields=["user", "-created_at"], name="on_chain_pa_user_id_f14220_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onchainpayment",
            index=models.Index(
                fields=["transaction_hash"], name="on_chain_pa_transac_c3df9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onchainpayment",
            index=models.Index(fields=["status"], name="on_chain_pa_status_37155c_idx"),
        ),
    ]
