# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                ("course_title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("total_modules", models.IntegerField(default=0)),
                ("modules_completed", models.IntegerField(default=0)),
                ("total_lessons", models.IntegerField(default=0)),
                ("lessons_completed", models.IntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("total_quizzes", models.IntegerField(default=0)),
                ("quizzes_passed", models.IntegerField(default=0)),
                (
                    "average_quiz_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_time_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("tokens_earned", models.IntegerField(default=0)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("certificate_issued_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_id", models.IntegerField()),
                ("lesson_title", models.CharField(max_length=255)),
                ("course_id", models.IntegerField()),
                ("module_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_spent_minutes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "video_watched_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of video watched (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("resources_downloaded", models.IntegerField(default=0)),
                ("tokens_earned", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "lesson_progress",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.IntegerField()),
                ("module_title", models.CharField(max_length=255)),
                ("course_id", models.IntegerField()),
                ("total_lessons", models.IntegerField(default=0)),
                ("lessons_completed", models.IntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("total_quizzes", models.IntegerField(default=0)),
                ("quizzes_passed", models.IntegerField(default=0)),
                (
                    "average_quiz_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_time_minutes", models.IntegerField(default=0)),
                ("tokens_earned", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "module_progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                ("lessons_completed", models.IntegerField(default=0)),
                ("quizzes_passed", models.IntegerField(default=0)),
                (
                    "average_quiz_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_time_minutes", models.IntegerField(default=0)),
                ("tokens_earned", models.IntegerField(default=0)),
                ("snapshot_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "progress_snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.IntegerField()),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_response", models.TextField()),
                ("points_possible", models.IntegerField(default=1)),
                ("points_earned", models.IntegerField(default=0)),
                ("is_correct", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "question_responses",
                "ordering": ["question_id"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_id", models.IntegerField()),
                ("quiz_id", models.IntegerField()),
                ("quiz_title", models.CharField(max_length=255)),
                ("course_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "percentage_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("passing_score", models.IntegerField(default=70)),
                ("is_passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_minutes", models.IntegerField(default=0)),
                ("attempt_number", models.IntegerField(default=1)),
                ("tokens_earned", models.IntegerField(default=0)),
                (
                    "responses",
                    models.JSONField(
                        default=dict,
                        help_text="User answers to questions {question_id: answer}",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_attempts",
                "ordering": ["-completed_at"],
            },
        ),
    ]
