# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("progress_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="progresssnapshot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="quiz_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_responses",
                to="progress_service.quizattempt",
            ),
        ),
        migrations.AddIndex(
            model_name="courseprogress",
            index=models.Index(
                fields=["user", "status"], name="course_prog_user_id_7af724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprogress",
            index=models.Index(
                fields=["completion_percentage"], name="course_prog_complet_1b205c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseprogress",
            unique_together={("user", "course_id")},
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["user", "course_id"], name="lesson_prog_user_id_5ccbf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(fields=["status"], name="lesson_prog_status_3bf8ae_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("user", "lesson_id")},
        ),
        migrations.AlterUniqueTogether(
            name="moduleprogress",
            unique_together={("user", "module_id")},
        ),
        migrations.AlterUniqueTogether(
            name="progresssnapshot",
            unique_together={("user", "course_id", "snapshot_date")},
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["user", "quiz_id"], name="quiz_attemp_user_id_558d63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["is_passed"], name="quiz_attemp_is_pass_93f66a_idx"
            ),
        ),
    ]
