# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(unique=True)),
                ("course_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(default=list, help_text="List of course tags"),
                ),
                (
                    "feature_vector",
                    models.JSONField(
                        default=dict,
                        help_text="Feature vector for content-based filtering",
                    ),
                ),
                ("total_enrollments", models.IntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_vectors",
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_name", models.CharField(max_length=255)),
                (
                    "courses_in_path",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of course IDs in learning path",
                    ),
                ),
                ("current_course_index", models.IntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("estimated_completion_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "learning_paths",
            },
        ),
        migrations.CreateModel(
            name="RecommendationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="List of recommended courses with scores",
                    ),
                ),
                ("algorithm_version", models.CharField(default="v1", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(help_text="Cache expiration time")),
            ],
            options={
                "db_table": "recommendation_cache",
            },
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_course_id", models.IntegerField()),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("already_taken", "Already Taken"),
                            ("not_interested", "Not Interested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommendation_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCourseInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("enroll", "Enrolled"),
                            ("complete", "Completed"),
                            ("rate", "Rated"),
                            ("bookmark", "Bookmarked"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "interaction_strength",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Weight of interaction (0-1)",
                        max_digits=3,
                    ),
                ),
                ("time_spent_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_course_interactions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_categories",
                    models.JSONField(
                        default=list, help_text="List of preferred course categories"
                    ),
                ),
                (
                    "preferred_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("video", "Video Lectures"),
                            ("text", "Text-based"),
                            ("interactive", "Interactive"),
                            ("project_based", "Project-based"),
                        ],
                        default="video",
                        max_length=50,
                    ),
                ),
                (
                    "avg_rating_given",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("courses_completed", models.IntegerField(default=0)),
                ("courses_enrolled", models.IntegerField(default=0)),
                ("total_ratings_given", models.IntegerField(default=0)),
                ("last_interaction", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
    ]
