# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_path",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recommendationcache",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_cache",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recommendationfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercourseinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationfeedback",
            unique_together={("user", "recommended_course_id")},
        ),
        migrations.AddIndex(
            model_name="usercourseinteraction",
            index=models.Index(
                fields=["user", "-updated_at"], name="user_course_user_id_fae2f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercourseinteraction",
            index=models.Index(
                fields=["course_id", "-updated_at"],
                name="user_course_course__348deb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercourseinteraction",
            unique_together={("user", "course_id", "interaction_type")},
        ),
    ]
