from dotenv import load_dotenv
import os

load_dotenv()

WEB3_SEPOLIA_RPC = os.getenv("SEPOLIA_RPC_URL")
PRIVATE_KEY = os.getenv("PRIVATE_KEY")
PLATFORM_TREASURY_ADDRESS = os.getenv("PLATFORM_TREASURY_ADDRESS")
ERC20_CONTRACT_ADDRESS = os.getenv("ERC20_CONTRACT_ADDRESS")
ERC721_CONTRACT_ADDRESS = os.getenv("ERC721_CONTRACT_ADDRESS")
AP2_CONTRACT_ADDRESS = os.getenv("AP2_CONTRACT_ADDRESS")