# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stripepurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="stripe_purchase",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund",
                to="payment_service.stripepurchase",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="stripe_purchase",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="payment_service.stripepurchase",
            ),
        ),
        migrations.AddField(
            model_name="stripepurchase",
            name="token_package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment_service.tokenpackage",
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["event_id"], name="stripe_webh_event_i_f749e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["event_type"], name="stripe_webh_event_t_a1d4c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripepurchase",
            index=models.Index(
                fields=["user", "-created_at"], name="stripe_purc_user_id_e549cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripepurchase",
            index=models.Index(fields=["status"], name="stripe_purc_status_8a4632_idx"),
        ),
        migrations.AddIndex(
            model_name="stripepurchase",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="stripe_purc_stripe__4437ce_idx",
            ),
        ),
    ]
