# Generated by Django 5.2.7 on 2025-11-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminDashboardLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_banned", "User Banned"),
                            ("user_deleted", "User Deleted"),
                            ("course_approved", "Course Approved"),
                            ("course_rejected", "Course Rejected"),
                            ("course_deleted", "Course Deleted"),
                            ("token_distributed", "Token Distributed"),
                            ("payment_refunded", "Payment Refunded"),
                            ("certificate_verified", "Certificate Verified"),
                            ("fraud_detected", "Fraud Detected"),
                            ("settings_updated", "Settings Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.IntegerField()),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "admin_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_key", models.CharField(max_length=100, unique=True)),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("token_reward", "Token Reward"),
                            ("payment_config", "Payment Configuration"),
                            ("blockchain_config", "Blockchain Configuration"),
                            ("email_config", "Email Configuration"),
                            ("rate_limit", "Rate Limiting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_settings",
                "ordering": ["setting_key"],
            },
        ),
        migrations.CreateModel(
            name="FraudDetectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fraud_type",
                    models.CharField(
                        choices=[
                            ("multiple_accounts", "Multiple Accounts"),
                            ("token_manipulation", "Token Manipulation"),
                            ("payment_chargeback", "Payment Chargeback"),
                            ("suspicious_login", "Suspicious Login"),
                            ("fake_certificates", "Fake Certificates"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("bot_activity", "Bot Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed Fraud"),
                            ("false_positive", "False Positive"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("action_taken", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "fraud_detection_logs",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("total_courses", models.IntegerField(default=0)),
                ("total_enrollments", models.IntegerField(default=0)),
                (
                    "total_tokens_distributed",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("active_users_today", models.IntegerField(default=0)),
                ("active_users_week", models.IntegerField(default=0)),
                ("active_users_month", models.IntegerField(default=0)),
                ("total_lessons_completed", models.IntegerField(default=0)),
                (
                    "average_course_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "platform_uptime_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_metrics",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
