# Generated by Django 5.2.7 on 2025-11-01 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admindashboardlog",
            name="admin_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminsettings",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_frauds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="systemmetrics",
            index=models.Index(
                fields=["-recorded_at"], name="system_metr_recorde_cc2e0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admindashboardlog",
            index=models.Index(
                fields=["-created_at"], name="admin_logs_created_9b3687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admindashboardlog",
            index=models.Index(
                fields=["admin_user", "-created_at"],
                name="admin_logs_admin_u_eac129_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="frauddetectionlog",
            index=models.Index(
                fields=["status", "-created_at"], name="fraud_detec_status_484b36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frauddetectionlog",
            index=models.Index(
                fields=["user", "-created_at"], name="fraud_detec_user_id_0190a0_idx"
            ),
        ),
    ]
